### ISSUE TITLE
Playing an alarm sound

### ISSUE THREAD

**Issue by DavidGarfinkle** [ehymowitz/alarm-sharer#2]
We need to ask the system to play an audio file

There are a few implementation options

## expo-av

Implement the sound playback using expo sound API

The gotcha here is that we need this to elevate our app permissions to play this sound from the background

here's a stackoverflow example https://stackoverflow.com/questions/61671304/how-to-play-background-audio-in-react-native-using-expo-av

## expo push notifications

Handle the background gotcha with a system handled push notification 

- possibly working for android
- Not working for iOS:  expo issues number 12969 

## pass to system alarm

Since there isn't an expo-alarm API, we'd call directly into the Android or iOS libraries and schedule an alarm 

- call into Android's `AlarmManager` and iOS equivalent
- requires us to handle app builds separately with Studio and XCode

**Comment by ehymowitz** [comment]
solution built by downloading the audio file to device storage and calling `AlarmManager` see [this repo for native code ](https://github.com/ehymowitz/custom-alarm-sounds)
